name: "Install Dependencies"
description: "Install Salesforce CLI, Java, and other necessary dependencies"
runs:
  using: "composite"
  steps:
    # - name: "Install Salesforce CLI"
    #   shell: bash
    #   run: npm install @salesforce/cli --global

    - name: "Installing SF git delta"
      shell: bash
      run: |
        echo y | sf plugins install sfdx-git-delta
        sf plugins

    - name: "Installing java"
      shell: bash
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt install default-jdk

    - name: "Installing SFDX scanner"
      shell: bash
      run: |
        echo y | sf plugins install @salesforce/sfdx-scanner
