name: "Check and Deploy"
description: "Check-only deploy delta changes and run specified tests"
inputs:
  APEX_TESTS:
    description: "List of Apex test classes to run"
    required: false
  TEST_LEVEL:
    description: "Apex testing level for deployment"
    required: true
    default: "RunSpecifiedTests"
    options:
      - "RunSpecifiedTests"
      - "RunLocalTests"
      - "RunAllTestsInOrg"
  ORG_ALIAS:
    description: "Alias for the Salesforce org"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check and Deploy"
      shell: bash
      run: |
        sf project deploy start --source-dir "changed-sources/force-app" --dry-run --target-org ${{ inputs.ORG_ALIAS }} --ignore-conflicts
      # run: |
      #   tests=""
      #   for class in ${{ inputs.APEX_TESTS }}; do
      #     tests+=" --tests $class"
      #   done
      #   sf project deploy validate --source-dir "changed-sources/force-app" --test-level ${{ inputs.TEST_LEVEL }} $tests --target-org ${{ inputs.ORG_ALIAS }}
