name: Salesforce Metadata Code Scan
description: Performs a static code analysis on repo 

branding:
  icon: code
  color: blue

inputs:
  DRY_RUN:
    description: "Validate deploy and run Apex tests but don't save to the org."
    type: boolean
  TEST_LEVEL:
    description: "Deployment Apex testing level."
    type: choice
    default: RunLocalTests
    options:
      - NoTestRun
      - RunSpecifiedTests
      - RunLocalTests
      - RunAllTestsInOrg
  WAIT:
    description: "Number of minutes to wait for command to complete and display results."
    type: number
    default: 30
  SOURCE_DIRECTORY:
    description: "Path to the local source files to deploy."
    type: string
    default: force-app
  SFDX_AUTH_URL:
    description: "The auth url tied to your deployment environment"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
        sf --version
    - name: Install SF Code Scanning Tools
      shell: bash
      run: |
        sf plugins:install @salesforce/sfdx-scanner
    - name: Execute SF Code Scan and output to CSV.
      shell: bash
      run: |
        sf scanner run -t .\force-app\ -f csv > uat-scanner-out.csv