name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - gm_crm2_training
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on ${{ vars.ENVIRONMENT_NAME }}
        uses: ./.github/actions/sf-deploy-action.yml
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true